name: Generar gráfica

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generar-grafica:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -s http://localhost:9200/_cluster/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checar repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib elasticsearch==8.8.1

    - name: Esperar a que Elasticsearch esté listo
      run: |
        echo "Esperando a que Elasticsearch esté listo..."
        until curl -s http://localhost:9200 >/dev/null; do sleep 5; done

    - name: Ejecutar script
      run: python mi_script.py

    - name: Subir gráfica como artifact
      uses: actions/upload-artifact@v4
      with:
        name: grafica
        path: grafica.png
