name: Generar gráfica

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generar-grafica:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib elasticsearch==8.8.1

    - name: Ejecutar script
      run: python mi_script.py

    - name: Subir gráfica como artifact
      uses: actions/upload-artifact@v4
      with:
        name: grafica
        path: grafica.png
